; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
lib_dir = ../../sdk/lib

[env:v2]
platform = espressif32 @ ^6.6.0
board = lilka_v2
framework = arduino
lib_extra_dirs = ./lib
; Define LILKA_BREADBOARD to lower SPI speed to 40 MHz (instead of normal 80)
; TODO: Remove this when we have PCBs!
; build_flags = -D LILKA_BREADBOARD -D LILKA_NO_SPLASH
build_flags =
	-D LILKA_NO_SPLASH
	-D DOOM_FFC_ST7796U=1
	-D EXT_TFT_INIT_SPI_HZ=15000000UL
	-D EXT_TFT_BULK_SPI_HZ=125000000UL
	-D EXT_TFT_CHUNK_ROWS=4
extra_scripts = move_firmware.py
lib_deps =
	lilka/Lilka @ ^2.3.0
